# Generated by Django 3.0.3 on 2020-03-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='category',
            field=models.CharField(choices=[('LOV', 'Love'), ('CRS', 'Crush'), ('M&S', 'Mom&Son'), ('D&S', 'Dad&Son'), ('B&S', 'Brother&Sister'), ('BFF', 'BestFriend'), ('RLV', 'Relatives'), ('HAT', 'Hatters'), ('TCR', 'Teacher'), ('RML', 'Role Model'), ('SUP', 'Supporters'), ('COL', 'Colleague')], default='LOV', max_length=3),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='title',
            field=models.TextField(max_length=50),
        ),
    ]
