# Generated by Django 3.0.3 on 2020-03-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poetry',
            name='category',
            field=models.CharField(choices=[('LOV', 'Love'), ('MOT', 'Motivational'), ('ATD', 'Attitude'), ('LIF', 'Life'), ('FRD', 'Friendship'), ('GOD', 'Gods'), ('MOM', 'Mother'), ('NAT', 'Nature')], default='LOV', max_length=3),
        ),
    ]
